"""
PendingInvite — stores invite tokens for users who clicked an invite link
but were not yet logged in. After login/signup, the backend checks this
table and auto-adds them to the event as an attendee.
"""

from datetime import datetime
from sqlalchemy import DateTime, String, Integer, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.models import Base


class PendingInvite(Base):
    __tablename__ = "pending_invites"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    event_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("events.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # The invite token that was used — so we know which event to add them to
    invite_token: Mapped[str] = mapped_column(String, nullable=False, index=True)
    # Temporary session token generated by the frontend and stored in localStorage
    # Used to match the pending invite back to the user after login
    session_token: Mapped[str] = mapped_column(
        String, nullable=False, unique=True, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )

    event: Mapped["Event"] = relationship("Event", back_populates="pending_invites")
