"""Add flyers to events

Revision ID: 04da1380e233
Revises: 13bd93bae4f8
Create Date: 2026-03-17 01:36:43.556577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04da1380e233'
down_revision: Union[str, Sequence[str], None] = '13bd93bae4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('flyer_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'flyer_url')
    # ### end Alembic commands ###
